name: telegram_fastnews

on:
  schedule:
    - cron: '10 23,2,4,8,12 * * * '
  watch:
    types: [started]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: 'Set up Python'
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
         
      - name: 'Install requirements'
        run: pip install -r ./Q_sub/requirements.txt 
        
      - name: '公众号iosrule' 
        run: python3 ./telegram/fastnews.py
        env:
            DJJ_TELE_GROUP: ${{ secrets.DJJ_TELE_GROUP }}
